create extension if not exists "pgcrypto";

create table if not exists fatalities (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  type text not null default 'feature' check (type in ('feature', 'project')),
  title text not null,
  brand text not null,
  sector text not null,
  product_type text not null,
  total_loss text not null,
  start_year integer not null,
  end_year integer not null,
  intro_text text not null,
  failure_analysis text not null,
  market_analysis text not null,
  startup_learnings text not null,
  market_potential text not null,
  difficulty text not null,
  scalability text not null,
  pivot_concept text not null,
  execution_plan jsonb not null default '[]'::jsonb,
  monetization_strategy text not null,
  suggested_tech jsonb not null default '[]'::jsonb,
  author_name text not null,
  author_role text not null,
  is_ai_victim boolean not null default false,
  status text not null check (status in ('draft', 'published')),
  project_vision text,
  resources_burned text,
  reality_check text,
  missed_pivot text
);

alter table fatalities add column if not exists type text;
alter table fatalities add column if not exists project_vision text;
alter table fatalities add column if not exists resources_burned text;
alter table fatalities add column if not exists reality_check text;
alter table fatalities add column if not exists missed_pivot text;
alter table fatalities alter column type set default 'feature';
update fatalities set type = 'feature' where type is null;
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'fatalities_type_check'
  ) then
    alter table fatalities
    add constraint fatalities_type_check
    check (type in ('feature', 'project'));
  end if;
end
$$;

create table if not exists community_comments (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  fatality_id bigint not null references fatalities(id) on delete cascade,
  name text not null,
  email text not null,
  comment text not null
);

alter table fatalities enable row level security;
alter table community_comments enable row level security;

drop policy if exists "public read published fatalities" on fatalities;
create policy "public read published fatalities"
on fatalities
for select
using (status = 'published');

drop policy if exists "public insert fatalities" on fatalities;
create policy "public insert fatalities"
on fatalities
for insert
with check (true);

drop policy if exists "public update fatalities" on fatalities;
create policy "public update fatalities"
on fatalities
for update
using (true)
with check (status in ('draft', 'published'));

drop policy if exists "public insert comments" on community_comments;
create policy "public insert comments"
on community_comments
for insert
with check (true);

drop policy if exists "public read comments" on community_comments;
create policy "public read comments"
on community_comments
for select
using (true);
